# Generated by Django 5.2.8 on 2025-11-29 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=10, verbose_name='Tipo de conteúdo')),
                ('arquivo_url', models.URLField(verbose_name='URL do conteúdo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='DesafioOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do desafio')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('nivel_dificuldade', models.CharField(max_length=50, verbose_name='Nível de dificuldade')),
                ('pontos_recompensa', models.IntegerField(verbose_name='Pontos de recompensa')),
            ],
            options={
                'verbose_name': 'Desafio Offline',
                'verbose_name_plural': 'Desafios Offline',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da recompensa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pontos_necessarios', models.IntegerField(verbose_name='Pontos necessários para desbloquear')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Número de telefone inválido')], verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='RotinaTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_minutos', models.IntegerField(verbose_name='Limite diário (minutos)')),
                ('atividades_offline_planejadas', models.TextField(verbose_name='Atividades offline planejadas')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rotina de Tempo de Tela',
                'verbose_name_plural': 'Rotinas de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='RegistroTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('minutos_uso', models.IntegerField(verbose_name='Minutos de uso')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Tempo de Tela',
                'verbose_name_plural': 'Registros de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
            options={
                'ordering': ['posicao'],
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('usuarios', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('atividade_realizada', models.TextField(verbose_name='Atividade realizada')),
                ('tempo_tela_utilizado', models.IntegerField(verbose_name='Tempo de tela utilizado (minutos)')),
                ('reflexao', models.TextField(blank=True, verbose_name='Reflexão do dia')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
            },
        ),
        migrations.CreateModel(
            name='ConquistaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(verbose_name='Data da conclusão')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desafiooffline', verbose_name='Desafio')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conquista de Desafio',
                'verbose_name_plural': 'Conquistas de Desafios',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('limite_excedido', 'Limite de Tela Excedido'), ('desafio_disponivel', 'Desafio Disponível'), ('recompensa_disponivel', 'Recompensa Disponível')], max_length=50, verbose_name='Tipo de alerta')),
                ('mensagem', models.TextField(verbose_name='Mensagem do alerta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
