# Generated by Django 5.2.1 on 2025-06-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=10, verbose_name='Tipo de conteúdo')),
                ('arquivo_url', models.URLField(verbose_name='URL do conteúdo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Conteúdo Educativo',
                'verbose_name_plural': 'Conteúdos Educativos',
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da criança')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('tempo_tela_diario', models.IntegerField(verbose_name='Tempo de tela diário (min)')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
            },
        ),
        migrations.CreateModel(
            name='DesafioOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do desafio')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('nivel_dificuldade', models.CharField(max_length=50, verbose_name='Nível de dificuldade')),
                ('pontos_recompensa', models.IntegerField(verbose_name='Pontos de recompensa')),
            ],
            options={
                'verbose_name': 'Desafio Offline',
                'verbose_name_plural': 'Desafios Offline',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da recompensa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pontos_necessarios', models.IntegerField(verbose_name='Pontos necessários para desbloquear')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do responsável')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='ConquistaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(verbose_name='Data da conclusão')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desafiooffline', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Conquista de Desafio',
                'verbose_name_plural': 'Conquistas de Desafios',
            },
        ),
        migrations.CreateModel(
            name='RegistroTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('minutos_uso', models.IntegerField(verbose_name='Minutos de uso')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Registro de Tempo de Tela',
                'verbose_name_plural': 'Registros de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='RotinaTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_minutos', models.IntegerField(verbose_name='Limite diário (minutos)')),
                ('atividades_offline_planejadas', models.TextField(verbose_name='Atividades offline planejadas')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Rotina de Tempo de Tela',
                'verbose_name_plural': 'Rotinas de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='crianca',
            name='vinculo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Responsável'),
        ),
    ]
