# Generated by Django 5.2.1 on 2025-11-27 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Vídeo'), ('imagem', 'Imagem')], max_length=10, verbose_name='Tipo de conteúdo')),
                ('arquivo_url', models.URLField(verbose_name='URL do conteúdo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Conteúdo Educativo',
                'verbose_name_plural': 'Conteúdos Educativos',
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da criança')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('tempo_tela_diario', models.IntegerField(verbose_name='Tempo de tela diário (minutos)')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
            },
        ),
        migrations.CreateModel(
            name='DesafioOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do desafio')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('nivel_dificuldade', models.CharField(max_length=50, verbose_name='Nível de dificuldade')),
                ('pontos_recompensa', models.IntegerField(verbose_name='Pontos de recompensa')),
            ],
            options={
                'verbose_name': 'Desafio Offline',
                'verbose_name_plural': 'Desafios Offline',
            },
        ),
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da recompensa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('pontos_necessarios', models.IntegerField(verbose_name='Pontos necessários para desbloquear')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('limite_excedido', 'Limite de Tela Excedido'), ('desafio_disponivel', 'Desafio Disponível'), ('recompensa_disponivel', 'Recompensa Disponível')], max_length=50, verbose_name='Tipo de alerta')),
                ('mensagem', models.TextField(verbose_name='Mensagem do alerta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='ConquistaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(verbose_name='Data da conclusão')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.desafiooffline', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Conquista de Desafio',
                'verbose_name_plural': 'Conquistas de Desafios',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('atividade_realizada', models.TextField(verbose_name='Atividade realizada')),
                ('tempo_tela_utilizado', models.IntegerField(verbose_name='Tempo de tela utilizado (minutos)')),
                ('reflexao', models.TextField(blank=True, verbose_name='Reflexão do dia')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Diário',
                'verbose_name_plural': 'Diários',
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos acumulados')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField(verbose_name='Posição no ranking')),
                ('pontuacao_total', models.IntegerField(verbose_name='Pontuação total')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
            },
        ),
        migrations.CreateModel(
            name='RegistroTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('minutos_uso', models.IntegerField(verbose_name='Minutos de uso')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Registro de Tempo de Tela',
                'verbose_name_plural': 'Registros de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='RotinaTempoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario_minutos', models.IntegerField(verbose_name='Limite diário (minutos)')),
                ('atividades_offline_planejadas', models.TextField(verbose_name='Atividades offline planejadas')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Rotina de Tempo de Tela',
                'verbose_name_plural': 'Rotinas de Tempo de Tela',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do responsável')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Insira um CPF com 11 dígitos numéricos.')], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Insira um telefone válido (8-15 dígitos, opcional +).')], verbose_name='Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='crianca',
            name='vinculo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Responsável'),
        ),
    ]
