# Generated by Django 5.2.1 on 2025-12-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='recompensas_resgatadas',
            field=models.ManyToManyField(blank=True, related_name='resgatados_por', to='app.recompensa'),
        ),
    ]
