# Generated by Django 5.2.1 on 2025-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='tempo_tela_diario',
            field=models.IntegerField(verbose_name='Tempo de tela diário (minutos)'),
        ),
    ]
