# Generated by Django 5.2.8 on 2025-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
    ]
