# Generated by Django 5.2.8 on 2025-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='area_atuacao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='usuario',
        ),
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(default='Sem especialidades', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(default='Sem especialidades', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(default='Sem especialidades', upload_to='profissionais/'),
            preserve_default=False,
        ),
    ]
